name: toughest
description: A new Flutter project.
version: 2.0.2+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie:
  share_plus:
  shrink_sidemenu:
  carousel_slider:
  url_launcher:
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints:
  mockito:
  test:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/local.json
    - assets/confetti.json

  fonts:
    - family: Acme
      fonts:
        - asset: assets/font/Acme-Regular.ttf
          weight: 600
    - family: Josefin Sans
      fonts:
        - asset: assets/font/JosefinSans-Regular.ttf
          weight: 200
